version: "3.3"

services:
  qbittorrent:
    image: trigus42/qbittorrentvpn
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        QBITTORRENT_TAG: ${QBITTORRENT_TAG}
      x-bake:
        platforms:
          - "linux/amd64"
          - "linux/arm/v6"
          - "linux/arm/v7"
          - "linux/arm64"
        pull: true
