name: docker-setup

description: Setup Docker environment for QEMU, Buildx, and registry logins

inputs:
  login_enabled:
    type: boolean
    description: "Enable or disable all logins"
    default: true
    required: false
  github_token:
    type: string
    description: "Set to enable GitHub Container Registry login"
    required: false
  dockerhub_username:
    type: string
    description: "Set to enable DockerHub login"
    required: false
  dockerhub_token:
    type: string
    description: "Set to enable DockerHub login"
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      if: ${{ inputs.login_enabled && inputs.github_token }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Login to Docker Hub
      if: ${{ inputs.login_enabled && inputs.dockerhub_username && inputs.dockerhub_token }}
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}
