version: "3.3"

services:
  qbittorrent:
    image: trigus42/qbittorrentvpn
    container_name: qbittorrent
    environment:
      - VPN_TYPE=openvpn
      - VPN_USERNAME=YOURUSERNAME
      - VPN_PASSWORD=YOURPASSWORD
    volumes:
      - './config/:/config'
    ports:
      - 80:8080
    restart: unless-stopped
    cap_add:
      - NET_ADMIN